### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by LuyaTools** [aithedev/skid-wiki#22]
Thanks for calling me a script kiddie :p
Btw the mercurial and blitzed fakes were not uploaded by me <3 keep it up tho🙏👆

**Comment by aithedevv** [comment]
who uploaded them then lmao

**Comment by LuyaTools** [comment]
Not me dude idk. But im still a skid kinda xd but imma change that <3

**Comment by aithedevv** [comment]
lmao okay bro

**Comment by accusable** [comment]
ok bro

**Comment by standfv** [comment]
He is scammer
beware of this scammer
![0C28BD4F-F4C6-4B59-932B-EC40B987EAF0](https://user-images.githubusercontent.com/27364465/215156430-8c7753a3-7e59-4944-90ab-c380561f2692.jpeg)
![D3F50F48-74BA-4E38-A53D-01CA166E134D](https://user-images.githubusercontent.com/27364465/215156457-5a699d1c-0c01-47b0-a499-8286e597fa4e.jpeg)
![209368C0-934D-431D-BBE7-9E021725CAC4](https://user-images.githubusercontent.com/27364465/215156470-f83ab096-7763-4470-83f3-c048aec82093.png)
