### ISSUE TITLE
Eric Dynasty

### ISSUE THREAD

**Issue by Exo-OX1564** [aithedev/skid-wiki#29]
Some kid called "Eric" 👁️ who cannot code with me on a vc and has to use his alts to act like he can code!

PLease whitelist him eRiC!!!!! ❗

**Comment by Exo-OX1564** [comment]
Also you call yourself a dev pfff how much are you paying to get these codes.

**Comment by aithedev** [comment]
dude what are you on 💀 

are you implying that im eric? who tf is that LMAOOO
